### ISSUE TITLE
API Consumption behind GCIP

### ISSUE THREAD

**Issue by somejavadev** [GoogleCloudPlatform/iap-gcip-web-toolkit#10]
Hi,

Would it be possible to describe how one would consume API's in programmatic fashion if the resource (REST API) is secured via GCIP?

As an example if you have a resource protected with GCIP that has both a Facebook and Google provider and you would want to access the resource from another Google project or completely externally.

Currently I am looking into something such as the following https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/iap in a combination with white listing the client id (from the 2nd project's service account) on the Google provider but it is not entirely clear to me how one should go about doing this.

Any advice would be appreciated.

**Comment by bojeil-google** [comment]
Hey @somejavadev, I don't understand your scenario which seems to inquire about multiple things.

Regarding programmatic access of resources gated with IAP external identities, you can refer to [Accessing non-Google resources programmatically](https://cloud.google.com/iap/docs/access-external-resources)

Regarding cross project access (IAP resource in one project and GCIP project in another), we do not currently support that. Though, I am not sure this is what you are asking.

**Comment by somejavadev** [comment]
Hi @bojeil-google, apologies if my question was not clear. I did a bit of digging and it seems the following is what I am after: https://cloud.google.com/iap/docs/service-accounts-external-identities although the documentation I found doesn't seem to be completely up to date or doesn't explain how you authorize different service accounts. Also the location of the client id mentioned in the documentation ("4 Select Show client ID from the overflow menu") doesn't seem to exist. In short I want to use a Google service account to access a GCIP protected resource.

**Comment by bojeil-google** [comment]
You get the client ID and secret by:

1. Going to Cloud Console
2. IAM & Admin -> Identity-Aware Proxy
3. **HTTPS RESOURCES** tab
4. In the row corresponding to your app (GCE or GAE, etc.)
5. Click the 3 dot button (overflow menu) and then the "Edit OAuth Client" option
6. This will take you to the OAuth client.

[Here](https://cloud.google.com/iap/docs/authentication-howto#authenticating_from_a_service_account) are the instructions on how to generate the Google ID token. They have samples in several languages.

**Comment by somejavadev** [comment]
Excellent, thank you @bojeil-google, that was the missing piece I needed. I appreciate your help.
