### ISSUE TITLE
Intermittently(!) receiving 'INVALID_OOB_CODE'

### ISSUE THREAD

**Issue by s3dse** [GoogleCloudPlatform/iap-gcip-web-toolkit#106]
I host a signin page on cloud run behind a iap-secured load balancer. The signin page uses firebase ui. The auth flow is controlled by two blocking functions: `before-create` and `before-signin`. In the `before-create` function I send an email with a verification link and a continue-url pointing back to the application:

```js
const link = await app.auth().generateEmailVerificationLink(email, {
    url: myAppURL
})
```

When I receive the verification mail and click the link I _sometimes_ get a page with success message and a continue button, just as expected. But _often times_ I see a message saying 'Your request to verify your email has expired or the link has already been used'. The traffic view tells me that the `oobCode` is invalid: 
```json{
{
    "error": {
        "code": 400,
        "message": "INVALID_OOB_CODE",
        "errors": [
            {
                "message": "INVALID_OOB_CODE",
                "domain": "global",
                "reason": "invalid"
            }
        ]
    }
}
```

I also tried to restrict the API Key by allowing only the $MY_APP.firebeseapp.com URL with no success. The issue still occurs now and then. 
How can I make the verification link work reliably with the continue-url?

**Comment by prameshj** [comment]
Please open a support case with GCP Cloud Support to investigate further, if you are still seeing this issue. Thanks!

**Comment by s3dse** [comment]
The problem only occurred when verifying the email on email-password authentication. I do not longer use this provider or out-of-band codes.
