### ISSUE TITLE
authui-container audit report shows 24 vulnerabilities (3 moderate, 18 high, 3 critical)

### ISSUE THREAD

**Issue by mausearce** [GoogleCloudPlatform/iap-gcip-web-toolkit#129]
Running `npm audit report`  on authui-container shows shows 24 vulnerabilities (3 moderate, 18 high, 3 critical)
Will this be addressed? Full output below.

# npm audit report

ansi-regex  3.0.0
Severity: high
Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix`
node_modules/wide-align/node_modules/ansi-regex

engine.io  4.0.0 - 6.2.0
Severity: high
Uncaught Exception in engine.io - https://github.com/advisories/GHSA-273r-mgr4-v34f
Uncaught exception in engine.io  - https://github.com/advisories/GHSA-r7qp-cfhv-p84w
fix available via `npm audit fix`
node_modules/engine.io
  socket.io  4.3.0 - 4.3.2
  Depends on vulnerable versions of engine.io
  node_modules/socket.io

karma  <6.3.16
Severity: moderate
Open redirect in karma - https://github.com/advisories/GHSA-rc3x-jf5g-xvc5
fix available via `npm audit fix`
node_modules/karma

loader-utils  <=1.4.1 || 2.0.0 - 2.0.3
Severity: critical
Prototype pollution in webpack loader-utils - https://github.com/advisories/GHSA-76p3-8jx3-jpfq
Prototype pollution in webpack loader-utils - https://github.com/advisories/GHSA-76p3-8jx3-jpfq
loader-utils is vulnerable to Regular Expression Denial of Service (ReDoS) via url variable - https://github.com/advisories/GHSA-3rfm-jhwj-7488
loader-utils is vulnerable to Regular Expression Denial of Service (ReDoS) via url variable - https://github.com/advisories/GHSA-3rfm-jhwj-7488
loader-utils is vulnerable to Regular Expression Denial of Service (ReDoS) - https://github.com/advisories/GHSA-hhq3-ff78-jv3g
loader-utils is vulnerable to Regular Expression Denial of Service (ReDoS) - https://github.com/advisories/GHSA-hhq3-ff78-jv3g
fix available via `npm audit fix`
node_modules/file-loader/node_modules/loader-utils
node_modules/loader-utils
node_modules/style-loader/node_modules/loader-utils
node_modules/ts-loader/node_modules/loader-utils
node_modules/url-loader/node_modules/loader-utils

minimatch  <3.0.5
Severity: high
minimatch ReDoS vulnerability - https://github.com/advisories/GHSA-f8q6-p94x-37v3
fix available via `npm audit fix --force`
Will install mocha@10.1.0, which is a breaking change
node_modules/minimatch
  mocha  5.1.0 - 9.2.1
  Depends on vulnerable versions of minimatch
  Depends on vulnerable versions of nanoid
  node_modules/mocha

minimist  <1.2.6
Severity: critical
Prototype Pollution in minimist - https://github.com/advisories/GHSA-xvch-5gv4-984h
fix available via `npm audit fix`
node_modules/minimist

nanoid  3.0.0 - 3.1.30
Severity: moderate
Exposure of Sensitive Information to an Unauthorized Actor in nanoid - https://github.com/advisories/GHSA-qrpm-p2h7-hrv2
fix available via `npm audit fix --force`
Will install mocha@10.1.0, which is a breaking change
node_modules/nanoid

node-fetch  <2.6.7
Severity: high
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g
fix available via `npm audit fix`
node_modules/node-fetch
  @firebase/auth  <=0.0.900-exp.f919db6a9 || 0.17.0-20217250818 - 0.19.6
  Depends on vulnerable versions of node-fetch
  node_modules/@firebase/auth
    firebase  0.800.3 - 0.900.25 || 7.9.1-0 - 7.9.1-canary.0396117e || 7.17.1-20206244562 - 7.17.1-canary.f1299756 || 7.17.2-20206291717 - 8.10.0 || 9.0.0-20217250818 - 9.6.4
    Depends on vulnerable versions of @firebase/auth
    Depends on vulnerable versions of @firebase/auth-compat
    Depends on vulnerable versions of @firebase/firestore
    Depends on vulnerable versions of @firebase/firestore-compat
    Depends on vulnerable versions of @firebase/functions
    Depends on vulnerable versions of @firebase/functions-compat
    Depends on vulnerable versions of @firebase/storage
    Depends on vulnerable versions of @firebase/storage-compat
    node_modules/firebase
  @firebase/auth-compat  <=0.2.6
  Depends on vulnerable versions of @firebase/auth
  Depends on vulnerable versions of node-fetch
  node_modules/@firebase/auth-compat
  @firebase/firestore  <=0.0.900-exp.f919db6a9 || 1.16.2-20206244562 - 1.16.2-canary.f1299756 || 1.16.3-20206291717 - 2.4.0 || 3.0.0-20217250818 - 3.4.3
  Depends on vulnerable versions of node-fetch
  node_modules/@firebase/firestore
    @firebase/firestore-compat  <=0.1.12
    Depends on vulnerable versions of @firebase/firestore
    node_modules/@firebase/firestore-compat
  @firebase/functions  <=0.0.900-exp.f919db6a9 || 0.4.51-202088235442 - 0.4.51-eap-auth-emulator.df41ee388 || 0.5.0-20209118324 - 0.6.15 || 0.7.0-20217250818 - 0.7.7
  Depends on vulnerable versions of node-fetch
  node_modules/@firebase/functions
    @firebase/functions-compat  <=0.1.8
    Depends on vulnerable versions of @firebase/functions
    node_modules/@firebase/functions-compat
  @firebase/storage  <=0.0.900-exp.f43d0c698 || 0.5.5-202151602035 - 0.5.5-canary.f6e1645ef || 0.5.6-20216122160 - 0.7.0 || 0.8.0-20217250818 - 0.9.1
  Depends on vulnerable versions of node-fetch
  node_modules/@firebase/storage
    @firebase/storage-compat  <=0.1.9
    Depends on vulnerable versions of @firebase/storage
    node_modules/@firebase/storage-compat

node-forge  <=1.2.1
Severity: high
Open Redirect in node-forge - https://github.com/advisories/GHSA-8fr3-hfg3-gpgp
Prototype Pollution in node-forge debug API. - https://github.com/advisories/GHSA-5rrq-pxf6-6jx5
Improper Verification of Cryptographic Signature in `node-forge` - https://github.com/advisories/GHSA-2r2c-g63r-vccr
Improper Verification of Cryptographic Signature in node-forge - https://github.com/advisories/GHSA-x4jg-mjrx-434g
Improper Verification of Cryptographic Signature in node-forge - https://github.com/advisories/GHSA-cfm4-qjh2-4765
URL parsing in node-forge could lead to undesired behavior. - https://github.com/advisories/GHSA-gf8q-jrpm-jvxq
No fix available
node_modules/node-forge
  gcip-iap  *
  Depends on vulnerable versions of node-forge
  node_modules/gcip-iap

protobufjs  6.11.0 - 6.11.2
Severity: high
Prototype Pollution in protobufjs - https://github.com/advisories/GHSA-g954-5hwp-pp24
fix available via `npm audit fix`
node_modules/protobufjs

socket.io-parser  4.0.0 - 4.0.4
Severity: critical
Insufficient validation when decoding a Socket.IO packet - https://github.com/advisories/GHSA-qm95-pgcg-qqfq
fix available via `npm audit fix`
node_modules/socket.io-parser

terser  5.0.0 - 5.14.1
Severity: high
Terser insecure use of regular expressions before v4.8.1 and v5.14.2 leads to ReDoS - https://github.com/advisories/GHSA-4wf5-vphf-c2xc
fix available via `npm audit fix`
node_modules/terser

24 vulnerabilities (3 moderate, 18 high, 3 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

**Comment by prameshj** [comment]
Thank you for filing this! We are auditing this and will patch it in the next release (or over 2 releases).

**Comment by prameshj** [comment]
The latest v0.1.13 version should be patched.
