### ISSUE TITLE
cannot start authui-container due to module not found

### ISSUE THREAD

**Issue by aaron-tillekeratne** [GoogleCloudPlatform/iap-gcip-web-toolkit#244]
Attempting to build and run the `Dockerfile` at `authui-container/` fails.

## Steps to recreate.
1. Build the container using `docker build -t authui .` 
2. Run the container using `docker run -it -p 8000:8000 authui`

## Expected behaviour
Start node app on specified port

## Observed behaviour
Throws the following error.

![image](https://github.com/GoogleCloudPlatform/iap-gcip-web-toolkit/assets/140357962/cff758c8-4db3-4f7f-8e21-7cc8d9fbc63c)

**Comment by bhparijat** [comment]
Hi, please comment your directory structure.

**Comment by aaron-tillekeratne** [comment]
![image](https://github.com/GoogleCloudPlatform/iap-gcip-web-toolkit/assets/140357962/1f84e359-ee99-4232-8c8d-2feaa1cfcb40)
 
This is as checked out from github

**Comment by aaron-tillekeratne** [comment]
Closing this due to lack of response.
