### ISSUE TITLE
authui-container won't load on Internet Explorer and Edge Legacy

### ISSUE THREAD

**Issue by neil-williamson** [GoogleCloudPlatform/iap-gcip-web-toolkit#27]
On arrival at the authui-container interface using IE or pre-Chromium Edge, I see a constant spinner - the page never loads or redirects forwards.  I've seen this using both an immediateFederatedRedirect and the identity-first tenant selection UI.

On Edge, the browser debug console displays the following:
```
0: Invalid argument       script.js (15,1426)
```
On IE, no errors appear to be recorded.

**Comment by bojeil-google** [comment]
Hey @neil-williamson, we have limited support in IE. I think IE 11 is the oldest version some of our dependencies support:
https://firebase.google.com/support/guides/environments_js-sdk

I was able to recreate the pre-Chromium Edge issue. Not sure about the root cause yet. We will investigate it.

**Comment by bojeil-google** [comment]
It seems the issue is related to the `authui-container` and not the `gcip-iap` module or our other dependencies.

**Comment by bojeil-google** [comment]
Hey @neil-williamson, the issue should be fixed in [v0.1.5](https://github.com/GoogleCloudPlatform/iap-gcip-web-toolkit/pull/29) of the `authui-container`.

Follow instructions [here](https://cloud.google.com/iap/docs/cloud-run-sign-in#redeploy) on how to deploy a revision.

**Comment by bojeil-google** [comment]
I was able to test it in IE11 and Edge pre-Chromium.

**Comment by neil-williamson** [comment]
Looks good to me.  Many thanks!
