### ISSUE TITLE
gcr.io/gcip-iap/authui: Consistently getting "Invalid API key" with latest image

### ISSUE THREAD

**Issue by tmc** [GoogleCloudPlatform/iap-gcip-web-toolkit#50]
I'm only getting "Invalid API key" when visiting the login page at the root URL.

Interestingly, /admin works and I've authed successfully (after adding Google as a top level idp).

A notable part of the stack is this:
```
this.sharedSettings = e && e.apiKey === r.apiKey ? e : new ut(r.apiKey,n);
...
return t.ciapAuth = new s.Authentication(i,void 0,e.HOSTED_UI_VERSION),
```
which is this line:
https://github.com/GoogleCloudPlatform/iap-gcip-web-toolkit/blob/517e574ae1d8d2df5bd141f6edcbdd56ba1f9fb1/authui-container/src/sign-in-ui.ts#L97

The sharedSettings call is in this method:
```js
function t(t, e, n) {
            if (this.handler = t,
            !function(t) {
                return !(!u(t) || "function" != typeof t.getAuth || "function" != typeof t.startSignIn || "function" != typeof t.completeSignOut || void 0 !== t.showProgressBar && "function" != typeof t.showProgressBar || void 0 !== t.hideProgressBar && "function" != typeof t.hideProgressBar || void 0 !== t.handleError && "function" != typeof t.handleError || void 0 !== t.processUser && "function" != typeof t.processUser || void 0 !== t.selectTenant && "function" != typeof t.selectTenant)
            }(t))
                throw new O(L["invalid-argument"],"Invalid AuthenticationHandler");
            try {
                var r = new ht(g(window),function(t) {
                    return void 0 === t && (t = window),
                    k(t) ? t.history.state : null
                }(window));
                this.sharedSettings = e && e.apiKey === r.apiKey ? e : new ut(r.apiKey,n);
                try {
                    this.handler.languageCode = r.hl
                } catch (e) {}
                switch (r.mode) {
                case ft.Login:
                    this.operationHandler = new gt(r,t,this.sharedSettings);
                    break;
                case ft.Reauth:
                    this.operationHandler = new gt(r,t,this.sharedSettings,!0);
                    break;
                case ft.Signout:
                    this.operationHandler = new bt(r,t,this.sharedSettings);
                    break;
                case ft.SelectAuthSession:
                    this.operationHandler = new mt(r,t,this.sharedSettings);
                    break;
                default:
                    throw new O(L["invalid-argument"],"Invalid mode")
                }
            } catch (t) {
                this.fatalError = t
            }
        }
```
I'm not easily/quickly finding the original source code for this so I'm a bit at a loss.

Note that I started this via the built-in IAP-initiated Cloud Run hosting.
/versionz reports 0.1.9

The image is gcr.io/gcip-iap/authui@sha256:db842770d654782001b7aba24532458fdb9ef9953b70ea2fcd162b2a133abf29

**Comment by bojeil-google** [comment]
Hey @tmc, you can't visit the sign in URL directly. You have to connect the sign in URL with an IAP resource first. Then you visit the IAP resource and it will redirect to the sign in UI with all the relevant parameters.

**Comment by tmc** [comment]
> Hey @tmc, you can't visit the sign in URL directly. You have to connect the sign in URL with an IAP resource first. Then you visit the IAP resource and it will redirect to the sign in UI with all the relevant parameters.

Ohh. OK. That's not super clear especially since the IAP settings page renders a link right to that login page.

**Comment by bojeil-google** [comment]
> > Hey @tmc, you can't visit the sign in URL directly. You have to connect the sign in URL with an IAP resource first. Then you visit the IAP resource and it will redirect to the sign in UI with all the relevant parameters.
> 
> Ohh. OK. That's not super clear especially since the IAP settings page renders a link right to that login page.

Yeah, the thing is the sign in page can be used to redirect to various projects or apps. For example, it could serve multiple tenants and each tenant has a different set of IdPs. It needs that initial context, otherwise it won't know what to do or show. However, we could possibly provide some default behavior to avoid this confusion. It's something we can definitely improve on. Thanks for the input, @tmc.
