### ISSUE TITLE
Coming back from redirect provider (google). Handling Error from blocking cloud function

### ISSUE THREAD

**Issue by MrVentzi** [GoogleCloudPlatform/iap-gcip-web-toolkit#57]
Used this as a starter: https://github.com/GoogleCloudPlatform/iap-gcip-web-toolkit/tree/master/sample/authui

My cloud function blocks signups for domain names that are not authorized.

The problem here is that it works fine, but I can't find a sensible way to handle it.

![image](https://user-images.githubusercontent.com/42213076/129072076-906cfe22-4737-4b60-8474-502887594143.png)

Tried putting up a console.log(error) inside handleError but doesn't seem to get to this point.
```
  public handleError(error) {
    console.log(error)
    this.updateError(error);
  }
```
the other option that i could see from docs is implementing the processUser, but I am not sue where the lastAuthUsed would be coming from?
```
processUser(user) {
  return lastAuthUsed..then(function(result) {
//do nothing
}, function(error) {
//handle error here...
});
}
```

Any ideas would be greatly appreciated.

Let me know if you need snippets of the code, although generally it pretty identical to the sample angular app.

**Comment by bojeil-google** [comment]
You need to make modifications to the code. Try doing this:
```
public startSignIn(auth: FirebaseAuth, selectedTenantInfo: ciap.SelectedTenantInfo): Promise<UserCredential> {
  return auth.getRedirectResult().catch((e) => ....)
    .then(() => {
      return new Promise((resolve, reject) => {
         ....
      });
    });
}
```

**Comment by MrVentzi** [comment]
Legend! Thank you @bojeil-google 

Apologies for misunderstanding how it should be done :)

**Comment by bojeil-google** [comment]
Cool. Glad it worked, @MrVentzi!

**Comment by MrVentzi** [comment]
I know I closed the ticket already, but one last question @bojeil-google 

Which of the `this.updateError(null);` is automatically hit when we come back from the google provider

Asking because if I add `this.updateError({code: "error", message: "Unauthorized"});` it doesn't show up when I come back, but if I comment out all the `this.updateError(null);` in the app (lazy find and replace), the error shows. So one of these is clearing it upon load.

Thanks again!

**Comment by MrVentzi** [comment]
Sorted. In case anyone comes across this, it was due to the `this.hideContainer();`

```
    if (this.code === "error-keep-once") {
      this.hideContainer();
      this.updateError({code: "error-keep-once", message: "Unauthorized"});
    } else {
      this.hideContainer();
    }
```
