### ISSUE TITLE
Programmatically define Identity Platform Settings triggers

### ISSUE THREAD

**Issue by SamyPesse** [GoogleCloudPlatform/iap-gcip-web-toolkit#58]
First of all, it's amazing to discover this feature, it's solving a lot of pain points we had with Firebase Auth and cloud functions (just missing the auth emulator support ;) ).

Is there an API or gcloud command to programmatically define the blocking triggers?

I'm trying to make sure it's correctly set during deployment for all of our dev projects (avoid user error when manual action is needed).

**Comment by bojeil-google** [comment]
Hey @SamyPesse, you can deploy the function with gcloud similar to deploying an HTTP trigger:
```
gcloud functions deploy beforeCreate --runtime nodejs12 --trigger-http --allow-unauthenticated
gcloud functions deploy beforeSignIn --runtime nodejs12 --trigger-http --allow-unauthenticated
```

You then need to enable the function with GCIP and register the URL. Something like:
```
curl -d "{'blockingFunctions':{'triggers':{'beforeCreate':{'functionUri':'https://[REGION]-[PROJECT_ID].cloudfunctions.net/[BEFORE_CREATE_FUNCTION_NAME]'},'beforeSignIn':{'functionUri':'https://[REGION]-[PROJECT_ID].cloudfunctions.net/[BEFORE_SIGNIN_FUNCTION_NAME]'}}}}" -H 'Authorization: Bearer [AUTH_TOKEN]' -X PATCH -H 'Content-Type: application/json' https://identitytoolkit.googleapis.com/admin/v2/projects/[PROJECT_ID]/config?updateMask=blockingFunctions.triggers
```
https://[REGION]-[PROJECT_ID].cloudfunctions.net/[BEFORE_CREATE_FUNCTION_NAME]: This is the beforeCreate function URI.
https://[REGION]-[PROJECT_ID].cloudfunctions.net/[BEFORE_SIGNIN_FUNCTION_NAME]: This is the beforeSignIn function URI.
[AUTH_TOKEN]: The OAuth access token.
[PROJECT_ID]: The Google Cloud project ID.
[REGION]: The region where the cloud function is deployed to.
[BEFORE_CREATE_FUNCTION_NAME]: The name of the exported beforeCreate function.
[BEFORE_SIGNIN_FUNCTION_NAME]: The name of the exported beforeSignIn function.

**Comment by SamyPesse** [comment]
Perfect! we are already using gcloud directly to deploy functions (`firebase deploy` was not working for us at scale).

It's great to know there is an API for this, I can plug it in our deploy script.

Any plan to support it as a firebase.json config and with something like `firebase deploy --only auth`?

**Comment by SamyPesse** [comment]
@bojeil-google the `AUH_TOKEN` requires which scope?

I'm trying with:

```ts
import { google } from 'googleapis';

...

const auth = new google.auth.GoogleAuth({
    scopes: [
        'https://www.googleapis.com/auth/cloud-platform',
        'https://www.googleapis.com/auth/firebase',
    ],
});
const authClient = await auth.getClient();
const project = await auth.getProjectId();

const data = {
    blockingFunctions: {
        triggers: {
            beforeSignIn: {
                functionUri: `https://${REGION}-${projectId}.cloudfunctions.net/users-beforeSignIn`,
            },
        },
    },
};

await authClient.request({
    url: `https://identitytoolkit.googleapis.com/admin/v2/projects/${projectId}/config?updateMask=blockingFunctions.triggers`,
    method: 'PATCH',
    data,
});
```

But it's failing with `data: { error: 'invalid_grant', error_description: 'Bad Request' },` on `url: 'https://oauth2.googleapis.com/token',`.

Do I need to define different scopes or do I need to use other credentials than the `gcloud` default one for my account?

**Comment by SamyPesse** [comment]
It works using a service account auth instead.

Closing this issue.
