### ISSUE TITLE
metadata.creationTime and lastSignInTime are invalid

### ISSUE THREAD

**Issue by SamyPesse** [GoogleCloudPlatform/iap-gcip-web-toolkit#60]
While logging the user passed `authClient.functions().beforeSignInHandler(callback)`'s callback, I'm getting:

<img width="676" alt="Screenshot 2021-08-12 at 14 33 06" src="https://user-images.githubusercontent.com/845425/129197448-31b5280f-6f2f-4fb8-9e90-bec7c3ba876c.png">

(For a user created today, 08/12/2021).

It looks like the date are incorrectly parsed/formatted.

**Comment by SamyPesse** [comment]
Quick investigation in the module source code indicates that the issue comes from `parseDate` in `user-record.js`, it seems to expect a UNIX timestamp, where it's parsing 1000*timestamp:

<img width="669" alt="Screenshot 2021-08-12 at 14 37 09" src="https://user-images.githubusercontent.com/845425/129197971-395ef5b9-f6e7-4efa-abce-da0e6f2c431f.png">
<img width="297" alt="Screenshot 2021-08-12 at 14 36 55" src="https://user-images.githubusercontent.com/845425/129197973-4a1a3064-d441-4069-bc8a-6ae51afd49ec.png">

I'm going to use a yarn patch as a workaround; but happy to make a PR if the source code is public

**Comment by bojeil-google** [comment]
Thanks for flagging this. The API returns them in units of seconds but it is likely this may be returned in milliseconds for blocking functions. The code was likely reused. We can investigate it and fix it.

**Comment by SamyPesse** [comment]
@bojeil-google do you think it'll be solved by a fix in the client module or by a change in the API?

I'm asking this question to know if we can rely on our patch for now, or if it may break at any point.

**Comment by bojeil-google** [comment]
This will be fixed in the client side module (e.g. not a backend fix).

**Comment by bojeil-google** [comment]
Sorry for the delay. The fix was released in v0.0.2.
