### ISSUE TITLE
Got "The bucket is not existed" and "API_KEY_HTTP_REFERRER_BLOCKED" when using authui-container v0.1.11 for sign-in page

### ISSUE THREAD

**Issue by minhvo91** [GoogleCloudPlatform/iap-gcip-web-toolkit#62]
Hello,

I deployed external identities, from GCP console IAP created a sign-in page on Cloud Run.

When accessing to my application the Sign-in throw an error as: "The bucket is not existed" in Cloud Run log

I also got this error "API_KEY_HTTP_REFERRER_BLOCKED" when access <sign-in-page>/admin

Could you please have a look on this issue?

Thanks!

**Comment by bojeil-google** [comment]
Hey @minhvo91 can you check you added any referrer restrictions on the API key? It sounds like it from the error message.

**Comment by minhvo91** [comment]
> Hey @minhvo91 can you check you added any referrer restrictions on the API key? It sounds like it from the error message.

Hi @bojeil-google , thank you for your reply.

I already solved the problem by adding <Sign-in page URL> and firebaseapp URL into Web Restriction in API configuration

Thanks a lot.
Minh
