### ISSUE TITLE
gcip-cloud-functions types are missing / not working in Typescript

### ISSUE THREAD

**Issue by cobraz** [GoogleCloudPlatform/iap-gcip-web-toolkit#91]
Hello,

Seems like the `package.json` is not referring to the correct types.

In package.json this is defined `"types": "./lib/index.d.ts",`, but it's all files are located in either `lib/cjs/index.d.ts` or `lib/esm/index.d.ts`.

**Comment by prameshj** [comment]
This should be fixed with https://www.npmjs.com/package/gcip-cloud-functions/v/0.0.3. Please reopen if this is not the case. Thanks!
